# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0003_auto_20170406_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Text'),
        ),
    ]
