# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0004_auto_20170406_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
