# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_auto_20170407_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedanswer',
            unique_together=set([('quiz', 'user'), ('question', 'answer')]),
        ),
    ]
