# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0012_auto_20170407_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedanswer',
            unique_together=set([]),
        ),
    ]
